{{- range $name, $values := .Values.module }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "application.fullname" (merge (dict "nameOfModule" $name) $ ) }}-env"
  labels:
    {{- include "template.labels" (merge (dict "name" $name) $) | nindent 4 }}
  {{- with $values.configmap.annotations }}
  annotations:
    {{- tpl (toYaml .) $ | nindent 8 }}
  {{- end }}
data:
  {{- if $values.env }}
  ## User Configs
  {{- range $setting, $option := $values.env }}
  {{ $setting }}: "{{ $option }}"
  {{- end }}
  {{- end }}
{{- end}}